let mapleader = ","
set backspace=indent,eol,start
set nu
set rnu
syntax on
set smartindent

set enc=utf-8

call plug#begin()
Plug 'preservim/nerdtree'
Plug 'morhetz/gruvbox'
Plug 'mattn/emmet-vim'
Plug 'vimwiki/vimwiki'
Plug 'vim-python/python-syntax'
call plug#end()
autocmd vimenter * colorscheme gruvbox
set background=dark    " Setting dark mode
cd ~/Desktop/
map <C-n> :NERDTreeToggle <CR>
set nocompatible
filetype plugin on
" sacar barras
set guioptions-=T
set guioptions-=r
set guioptions-=L
set guioptions-=m
" fonts
set guifont=Consolas:h12
" Window Navigation with Ctrl-[hjkl]
noremap <C-J> <C-W>j
noremap <C-K> <C-W>k
noremap <C-H> <C-W>h
noremap <C-L> <C-W>l

autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

set belloff=all

"Abrir terminal
map <F2> :belowright terminal<CR>
"Cambia el directorio automáticamente
set autochdir

tnoremap <ESC> <C-w>:q!<CR>

